name: Gerar APK AquaFlow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle 8.9
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Descompactar projeto
        run: |
          mkdir projeto
          unzip AquaFlow_V1_VSCode_LiveServer.zip -d projeto

      - name: Entrar na pasta do projeto
        run: |
          echo "Conteúdo:"
          find projeto -maxdepth 3 -type f | sort

      - name: Sincronizar arquivos Web
        run: |
          cd projeto/AquaFlow_V1
          chmod +x scripts/sync-web.sh
          ./scripts/sync-web.sh

      - name: Gerar APK
        run: |
          cd projeto/AquaFlow_V1
          gradle assembleDebug --stacktrace

      - name: Verificar APK
        run: |
          find projeto -name "*.apk" -type f -print

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: AquaFlow-APK
          path: projeto/AquaFlow_V1/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
